language: node_js
node_js:
  - 10

script:
  - npm test

after_success:
  # Setup rubygems creds
  - curl -u "$RUBYGEMS_USER:$RUBYGEMS_PW" https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials
  - chmod 0600 ~/.gem/credentials
  # this will short-circuit the publish step if it fails to interpolate $NPM_API_KEY
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"

deploy:
  # publish release candidates from any branch beginning with "release"
  - on:
      condition: $TRAVIS_BRANCH =~ ^release
      all_branches: true
      tags: false
    provider: script
    script:
      - script/release-candidate
    skip_cleanup: true

  # publish "final" releases on master
  - on:
      branch: master
      tags: false
    provider: script
    script: script/release
    skip_cleanup: true

notifications:
  slack: 'github:4OisIoqZYyMlWcw3hFtZgbmh'
