name: Deploy preview
on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.repository == 'primer/octicons' }}
    name: Build and deploy
    uses: primer/.github/.github/workflows/deploy_preview.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      node_version: 14
      install: yarn
      build: yarn build:docs:preview
      output_dir: docs/public
